steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/bi-model-development/uniswap-v3-info:$SHORT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/bi-model-development/uniswap-v3-info:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'uniswap-v3-info', '--region=us-central1', '--platform=managed', '--image=gcr.io/bi-model-development/uniswap-v3-info  :$SHORT_SHA']
timeout: 1200s
